{{- if and .Values.influxdb.enabled .Values.archival.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "stiebeleltron-stack.fullname" . }}-influxdb-task
  labels:
    {{- include "stiebeleltron-stack.labels" . | nindent 4 }}
data:
  task.flux: |
    import "strings"

    option task = {name: "Downsampling stiebeleltron", every: {{ .Values.archival.window }}}

    fromBucket = {{ .Values.influxdb.adminUser.bucket | quote }}
    targetBucket = {{ .Values.archival.bucket | quote }}

    from(bucket: fromBucket)
      |> range(start: -task.every)
      |> filter(fn: (r) => r._measurement =~ /^stiebeleltron_.+$/)
      |> drop(columns: ["url", "host"])
      |> aggregateWindow(every: task.every, fn: mean, createEmpty: false)
      |> to(bucket: targetBucket)
{{ (.Files.Glob "files/influxdb/*.sh").AsConfig | indent 2 }}
{{- end -}}
